### PR TITLE
Utils_GenericBrowser added resizable columns functionality

### PR DESCRIPTION
**Pull request by georgehristov**
Added a user resizable column functionality for the Utils_GenericBrowser module and adjusted Utils_RecordBrowser accordingly:
- fixed actions column
- exclude functionality when printing pdf

The resizable column functionality is built around the <a href="http://www.bacubacu.com/colresizable/">colResizable</a> JQuery plugin distributed under the MIT license and slightly modified to fit the purpose.
Modifications tested under EPESI 1.6.2.

### CODE REVIEW

**Comment by bukowskiadam** [comment]
I like this one. We should add some more fixed columns, like actions in mini_view, favorites or watchdog.
I think that you should make a pull request to col_resizable with your change for fixed columns. I've seen in the guest book that there is a need for that :)

What do you think about using localStorage instead of sessionStorage. It would persist column widths for certain domain name. There would be a conflict for two instances in subdirectories like that: http://example.com/epesi and http://example.com/crm - they would be interpreted as one installation, but it should be rare.

**Comment by georgehristov** [comment]
Now I have made the changes for mini_view and also fixed the favs and watchdog columns.

Regarding storing of column widths I would say we better concentrate on saving the user specific setting rather than one setting for a domain. Presently the setting is saved only as long as the window is open.

**Comment by georgehristov** [comment]
A few more fixes added

**Comment by bukowskiadam** [comment]
Indeed my suggestion will do user specific settings, unless more of them will use one browser. localStorage is per browser and hostname. So it's one setting for one domain on that specific browser.

**Comment by georgehristov** [comment]
You are correct and this is the next best thing to saving the setting for each user. And it is dead simple to implement so I have done it. Tested under Firefox and Chrome with EPESI 1.6.3.

**Comment by bukowskiadam** [comment]
I had to fix colResizable code, because I've got an error on every browser's window resize. Do you get it too?
Here is a fix: c16b5f444181ab68b285a823fe86d7f0711456f1

**Comment by georgehristov** [comment]
No, I have been using it on both Firefox 35.0.1 and Chrome 40.0 on 2 different computers and my colleagues are running the system as well but have not got an error.
Will apply the fix on my installation. Thanks.

**Comment by bukowskiadam** [comment]
For me firefox works well, but chrome give an error, even in private mode without extensions.

**Pull request merged**
