### PR TITLE
[FEATURE] introduce file field module

### PR DESCRIPTION
**Pull request by georgehristov**

### CODE REVIEW

**Comment by bukowskiadam** [comment]
Well, norbert is currently working on the generic file type to the recordbrowser. What a pity, that we don't share our current work (yet). I'll let him know about your pull request and we'll take best from both solutions.

**Comment by georgehristov** [comment]
Well, I could have issued a pull request earlier but I saw some comments by @jtylek in the forum that file field type is not really desirable having attachments module so I kept it for myself.
Maybe we can coordinate the efforts a bit with a roadmap?

**Comment by jtylek** [comment]
Yes - we need to better coordinate efforts. A roadmap, milestones - are needed.
Any serious ideas and especially work already started should be entered as an issue with a proper tag like "enhancement" - otherwise we will have situations like this one.

**Comment by georgehristov** [comment]
Agree but then the ball is on your side (for the updated roadmap at least) 😄

**Comment by jtylek** [comment]
You are absolutely right! @georgehristov 
👍 
But we are making some progress - we are starting our private repository to share more work - this will include public and private repositories: https://lab.telaxus.com/

**Comment by georgehristov** [comment]
Very good, I am in already 😄

**Comment by jtylek** [comment]
Great - I changed your access level from external to regular user. You can create groups and projects. We will use this platform for all public and private branches - only Epesi Core will remain on GitHub.

**Comment by NorbertNader** [comment]
@georgehristov What a coincidence... I actually started working on this not long ago. I have the file field in my repository NorbertNader/EPESI on branch testing, which is the only branch I have anyway... I went in a slightly different direction and used dropzone for uploading. I like that you made it a separate module. I think I will go that way as well. The only thing that I found inconvenient is that I have to add the file in a new base box, so I would probably stick with dropzone on this.

**Comment by georgehristov** [comment]
@NorbertNader It is up to you, any improvements are welcome. I am glad you did not go too far with this feature yet so my contribution will be useful.

**Comment by georgehristov** [comment]
Talking about drop zones: the drop zone on the `Utils_Attachment` module does not work and this bothers me a bit...maybe you can update it as well?

**Comment by jtylek** [comment]
@georgehristov and @NorbertNader 👍 
What is the status of this feature? I guess at this point Norbert would have to fix the drop zone?

**Comment by NorbertNader** [comment]
The Utils_attachment Files field does not have a dropzone, the only feature similar to dropzone is the copy/paste feature which seems to work, is this what you were referring to? I have not been updating the file field lately, I will however add the copy/paste feature to my repo so thanks for pointing that out despite it not being what you asked about.

**Comment by NorbertNader** [comment]
I just noticed this feature indeed does not work on safari. I don't think it is worth fixing in the current Utils_attachment File and just focus on polishing the current dropzone File field.

**Comment by georgehristov** [comment]
@NorbertNader: I did not figure out how to use the Ctrl+V feature neither in Chrome nor in Firefox.
Anyway I believe a dropzone is a must already so once you complete it for the other module you may implement it in Utils_Attachment I guess.
@jtylek: My Utils_FileField module is fully functional and can be used. Norbert is implementing a more advanced approach on it.

**Comment by NorbertNader** [comment]
Finally moved a bit forward with the file field. Added a new branch feature/file-field
Still plenty of issues, but the basic job, which is adding file field through record browser, and the dropzone with multiple files works.

**Comment by georgehristov** [comment]
Is there a reason you didn't use the Composer to auto-include the library files of the dropzone?

**Comment by NorbertNader** [comment]
Actually, yes there is. I modified Dropzone.prototype.removeFile. I will work on moving this out of dropzone to load it via composer.Though, I am leaning towards using package.json for requiring js libraries. Either way this is not a big deal imho, since it's only one library.

**Comment by georgehristov** [comment]
[filestorage-refactor](https://github.com/Telaxus/EPESI/tree/feature/filestorage-refactor) branch works quite good with only issues remaining the remote download and file history (and rewriting Utils_Attachment for it).
I am even about to use it on the production server as it comes very handy for I new module I am finishing now.
Any plan for this to be implemented or I can give it a try?

**Comment by NorbertNader** [comment]
Yes, I will get back to this starting tomorrow.

**Comment by bukowskiadam** [comment]
That's something I was going to finish, but I'm out of time right now.

**Comment by NorbertNader** [comment]
That's ok, I will do my best to finish the rest, not much left to do anyway. For now I [merged with master](https://github.com/Telaxus/EPESI/commit/d76ab50da8bc4d673b7ed3e675426a1484732889) and [removed the dropzone from lib and required it in composer](https://github.com/Telaxus/EPESI/commit/e045cfeb3d56b49c32e8f6fd93e08eb2158e6dd6). I am working on the Leightbox view, both for recordbrowser and admin->files, so please, bear with me...

**Comment by NorbertNader** [comment]
Ok, so the [remote file works](https://github.com/Telaxus/EPESI/commit/afdb8944d571866594bd136ceba0f78773ec98b1). Still have history left and attachments.

**Comment by georgehristov** [comment]
Previously the `$id` parameter of `Utils_FileStorageCommon::meta` method was referring to the id in `utils_filestorage_files` table where now using [this](https://github.com/Telaxus/EPESI/blob/feature/filestorage-refactor/modules/Utils/FileStorage/FileStorageCommon_0.php#L396) sql query it refers to the id in `utils_filestorage` table.
Is this a bug or a feature?

**Comment by NorbertNader** [comment]
I think it would be best if Adam addressed this question, but if I can speak from my point of view, I see it neither as a bug nor a feature. It's just what makes the most sense since the tables are broken into two now. You are most likely to get meta for a file via utils_filestorage id like [here](https://github.com/Telaxus/EPESI/blob/feature/filestorage-refactor/modules/Utils/FileStorage/ActionHandler.php#L105) since that is what is stored in the records file field. It actually eliminates the possibility of redundant code, since you always need to join on utils_filestorage_files id. Earlier it may not have been as necessary since only attachments used Utils_FileStorage. Maybe I am missing something, do you see a better approach?

**Comment by georgehristov** [comment]
So it is a feature (intended behaviour bringing advantage).
Then it must be considered that it is backward incompatible.
I was using the Utils_FileStorage module in my code /in the Utils_FileField module/ and having merged the filestorage-refactor branch the files retieved when calling `Utils_FileStorage::meta` method are different.

**Comment by NorbertNader** [comment]
Yes, I am aware that we have to make it backward compatible, but thank you for pointing that out. About it being a feature or not... I don't know, i see it more as a refactor since it does not introduce new funcionality.

**Comment by NorbertNader** [comment]
Actually, I forgot that Adam already added a patch for this [here](https://github.com/Telaxus/EPESI/commit/c280f7127d3daf364841872ff637623e1dd847cf), so it is backwards compatible for attachments.

**Comment by georgehristov** [comment]
Ok, then I suggest you add comment in the release notes so if anybody using the Utils_FileStorage module already he should patch his code as well.

**Comment by NorbertNader** [comment]
I will do so, thank you for the suggestion.

**Comment by NorbertNader** [comment]
I think I can merge the branch to master now, I [added history](https://github.com/Telaxus/EPESI/commit/65ee74e26e213c05740aea47198cf7cc019329d1) and everyhting seems to work well.

**Comment by georgehristov** [comment]
You will have to write a patch for creation of `utils_filestorage_remote` and `utils_filestorage_access` tables

**Comment by NorbertNader** [comment]
Thanks for the reminder, completely forgot about that.

**Comment by NorbertNader** [comment]
If you where getting a 'Dropzone not defined' on a  fresh installation composer.lock file was missing enyo/dropzone.

**Comment by georgehristov** [comment]
If there is the same file displayed several times on the screen (same file attached to different records in RB) the link click opens as many file leightbox prompts as the files displayed.

**Comment by NorbertNader** [comment]
That is strange, it should not do that as each leightbox has a unique id regardless of it being the same file or not, and how many records it is in. I tried it the way you described, I have two file fields in a recordset, both with the same file twice, I cloned that record, but I just don't see the issue, I alway get one leightbox... is this happening in the `GenericBrowser` view?

I did however notice that the leightbox was not displaying anything because the theme was not installed so I [fixed that](https://github.com/Telaxus/EPESI/commit/daed02ca5af6c1eb4a9c4989cae4bb2e08f21974)

**Pull request closed without merging**
