### PR TITLE
[UPDATE] sql for recursive access on single tab select fields

### PR DESCRIPTION
**Pull request by georgehristov**
Reference #63
I have tested a small update on QueryBuilder where it seems that it works fine with recursive access for single tab select fields at least.
I have tested with up to second level of recursive access and RB displays the results fine.
Please review and let me know if I missed out something as the access routine is quite complex.

### CODE REVIEW

**Comment by bukowskiadam** [comment]
I've used part of your idea, but have to fix it in several places. I will merge my code, but I have to decide if it's ok to put it in master as a fix or in dev for further testing. Stay tuned.

**Comment by bukowskiadam** [comment]
Please review a44f8192904c4a8a4075c2cba0cb7461842eb3ce.
I've decided to merge it into master.

**Comment by georgehristov** [comment]
You are quite bold :)
I will upload it to the our production server and start using it, let's see.

My idea for the recursive access on __RECORDSETS__ option is to call the recordsets crits to retrieve the possible tabs and then build a query using sql concat in the subquery to achieve the tab/id.

**Comment by bukowskiadam** [comment]
I don't get this `call the recordsets crits`. What do you mean?

At first I would start to thinking about finite multiple recordsets. For instance multiselect field just from two RS: company,contact (like customer field). I'm afraid about performance in case of more recordsets.

If we could assume that SQL optimizations works that the second condition is not evaluated, then we could build really long query like that:
```
(r.field contains 'company' AND EXISTS(select 1 from company_data c where <company access rules> AND r.field LIKE concat('%__company/', c.id, '__%'))
OR
(r.field contains 'contact' AND EXISTS(...)) 
```
*pseudo sql of course - just for the idea*

Listing all possible recordsets would produce really long query that could be really slow.

**Comment by georgehristov** [comment]
With `call the recordsets crits` I meant to use the crits callback which returns recordset=>crits array in case of \_\_RECORDSETS\_\_ option used for a select field.
Your code above is exactly what I meant, the list of recordsets retrieved as per above.
Of course there are performance concerns.
In any case the fix implemented now covers 95% of the cases (100% in my case), makes permission settings very clear and saves a lot of time. Thank you for taking up the issue and implementing the fix so quickly.

**Comment by bukowskiadam** [comment]
My current solution may lead to performance issues. We've found that query with nested query and `CONCAT(...)` is really slow:
```
SELECT r.* FROM premium_salesopportunity_data_1 AS r

 WHERE r.active=1 AND 
 (
     ((EXISTS (SELECT 1 FROM contact_data_1 AS r_contact_1 WHERE r_contact_1.active=1 AND ((r_contact_1.f_last_name LIKE ? AND r_contact_1.f_last_name IS NOT NULL) OR (r_contact_1.f_first_name LIKE ? AND r_contact_1.f_first_name IS NOT NULL)) AND r.f_employees LIKE CONCAT(\'%\\_\\_\', r_contact_1.id, \'\\_\\_%\'))))
)
```
It's the case when you're trying to search salesopportunity records by employees field (multiselect from contacts).
Access query uses the same SQL query schema - subquery with concat.

**Pull request closed without merging**
